#!/bin/bash
# An executable shell script wrapper around a Java Command Line Utility
# for making log entries 


#Edit the path below to indicate the location where the
#LogentryCLI.jar file resides.
if [ -r /cs/certified/apps/logentrycli/PRO/logentrycli.jar ] ; then
    JAR=/cs/certified/apps/logentrycli/PRO/logentrycli.jar
elif [ -r /apps/acctools/certified/apps/logentrycli/PRO/logentrycli.jar ] ; then
    JAR=/apps/acctools/certified/apps/logentrycli/PRO/logentrycli.jar
else
    echo "logentry cli is not properly installed."
fi

# Test if user has java in path
path_to_executable=$(which java)
if [ $? -eq 0 -a -x "$path_to_executable" ] ; then
   java -jar $JAR "$@"
else
   echo "Error: Java executable not found."
   echo "Please make sure java is set in your PATH environment variable."
   exit 1
fi

